import { ICard, ISeller } from '@/types/types';

export const SELLER_LIST: ISeller[] = [
  { id: 1, name: 'Truong Nguyen' },
  { id: 2, name: 'Hieu Le' },
  { id: 3, name: 'Nam Bac' },
];

export const CARD_LIST: ICard[] = [
  {
    id: 1,
    name: 'Monkey D. Luffy',
    price: 5.2,
    tier: 'Epic',
    unit: 'ETH',
    image: '/assets/cards/luffy.png',
    seller: SELLER_LIST[1],
  },
  {
    id: 2,
    name: 'Brook (Soul King)',
    price: 2.5,
    tier: 'Epic',
    unit: 'ETH',
    image: '/assets/cards/brook.png',
    seller: SELLER_LIST[1],
  },
  {
    id: 3,
    name: 'Monkey D. Garp',
    price: 1.2,
    tier: 'Epic',
    unit: 'ETH',
    image: '/assets/cards/garp.png',
    seller: SELLER_LIST[1],
  },
  {
    id: 4,
    name: 'Monkey D. Luffy',
    price: 5.2,
    tier: 'Epic',
    unit: 'ETH',
    image: '/assets/cards/luffy.png',
    seller: SELLER_LIST[1],
  },
  {
    id: 5,
    name: 'brook',
    price: 2.5,
    tier: 'Epic',
    unit: 'ETH',
    image: '/assets/cards/brook.png',
    seller: SELLER_LIST[0],
  },
  {
    id: 6,
    name: 'garp',
    price: 1.2,
    tier: 'Epic',
    unit: 'ETH',
    image: '/assets/cards/garp.png',
    seller: SELLER_LIST[2],
  },

  {
    id: 1,
    name: 'Monkey D. Luffy',
    price: 5.2,
    tier: 'Epic',
    unit: 'ETH',
    image: '/assets/cards/luffy.png',
    seller: SELLER_LIST[1],
  },
  {
    id: 2,
    name: 'Brook',
    price: 2.5,
    tier: 'Epic',
    unit: 'ETH',
    image: '/assets/cards/brook.png',
    seller: SELLER_LIST[1],
  },
  {
    id: 3,
    name: 'garp',
    price: 1.2,
    tier: 'Epic',
    unit: 'ETH',
    image: '/assets/cards/garp.png',
    seller: SELLER_LIST[1],
  },
  {
    id: 4,
    name: 'Monkey D. Luffy',
    price: 5.2,
    tier: 'Epic',
    unit: 'ETH',
    image: '/assets/cards/luffy.png',
    seller: SELLER_LIST[1],
  },
  {
    id: 5,
    name: 'brook',
    price: 2.5,
    tier: 'Epic',
    unit: 'ETH',
    image: '/assets/cards/brook.png',
    seller: SELLER_LIST[0],
  },
  {
    id: 6,
    name: 'garp',
    price: 1.2,
    tier: 'Epic',
    unit: 'ETH',
    image: '/assets/cards/garp.png',
    seller: SELLER_LIST[2],
  },

  {
    id: 1,
    name: 'Monkey D. Luffy',
    price: 5.2,
    tier: 'Epic',
    unit: 'ETH',
    image: '/assets/cards/luffy.png',
    seller: SELLER_LIST[1],
  },
  {
    id: 2,
    name: 'Brook',
    price: 2.5,
    tier: 'Epic',
    unit: 'ETH',
    image: '/assets/cards/brook.png',
    seller: SELLER_LIST[1],
  },
  {
    id: 3,
    name: 'garp',
    price: 1.2,
    tier: 'Epic',
    unit: 'ETH',
    image: '/assets/cards/garp.png',
    seller: SELLER_LIST[1],
  },
  {
    id: 4,
    name: 'Monkey D. Luffy',
    price: 5.2,
    tier: 'Epic',
    unit: 'ETH',
    image: '/assets/cards/luffy.png',
    seller: SELLER_LIST[1],
  },
  {
    id: 5,
    name: 'brook',
    price: 2.5,
    tier: 'Epic',
    unit: 'ETH',
    image: '/assets/cards/brook.png',
    seller: SELLER_LIST[0],
  },
  {
    id: 6,
    name: 'garp',
    price: 1.2,
    tier: 'Epic',
    unit: 'ETH',
    image: '/assets/cards/garp.png',
    seller: SELLER_LIST[2],
  },

  {
    id: 1,
    name: 'Monkey D. Luffy',
    price: 5.2,
    tier: 'Epic',
    unit: 'ETH',
    image: '/assets/cards/luffy.png',
    seller: SELLER_LIST[1],
  },
  {
    id: 2,
    name: 'Brook',
    price: 2.5,
    tier: 'Epic',
    unit: 'ETH',
    image: '/assets/cards/brook.png',
    seller: SELLER_LIST[1],
  },
  {
    id: 3,
    name: 'garp',
    price: 1.2,
    tier: 'Epic',
    unit: 'ETH',
    image: '/assets/cards/garp.png',
    seller: SELLER_LIST[1],
  },
  {
    id: 4,
    name: 'Monkey D. Luffy',
    price: 5.2,
    tier: 'Epic',
    unit: 'ETH',
    image: '/assets/cards/luffy.png',
    seller: SELLER_LIST[1],
  },
  {
    id: 5,
    name: 'brook',
    price: 2.5,
    tier: 'Epic',
    unit: 'ETH',
    image: '/assets/cards/brook.png',
    seller: SELLER_LIST[0],
  },
  {
    id: 6,
    name: 'garp',
    price: 1.2,
    tier: 'Epic',
    unit: 'ETH',
    image: '/assets/cards/garp.png',
    seller: SELLER_LIST[2],
  },
];
